// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbAgenciasVuelos
    {
        public int agenvuel_Id { get; set; }
        public string agenvuel_Nombre { get; set; }
    }
}