// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbCategoriasHabitacional
    {
        public tbCategoriasHabitacional()
        {
            tbHabitaciones = new HashSet<tbHabitaciones>();
        }

        public int cath_Id { get; set; }
        public string cath_Nombre { get; set; }

        public virtual ICollection<tbHabitaciones> tbHabitaciones { get; set; }
    }
}