// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbAeropuertos = new HashSet<tbAeropuertos>();
            tbHoteles = new HashSet<tbHoteles>();
        }

        public int ciud_Id { get; set; }
        public string ciud_Nombre { get; set; }
        public int depa_Id { get; set; }

        public virtual tbDepartamentos depa { get; set; }
        public virtual ICollection<tbAeropuertos> tbAeropuertos { get; set; }
        public virtual ICollection<tbHoteles> tbHoteles { get; set; }
    }
}