// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbContinentes
    {
        public tbContinentes()
        {
            tbPaises = new HashSet<tbPaises>();
        }

        public int cont_Id { get; set; }
        public string cont_Nombre { get; set; }

        public virtual ICollection<tbPaises> tbPaises { get; set; }
    }
}