// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public int depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int pais_Id { get; set; }

        public virtual tbPaises pais { get; set; }
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}