// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int estc_Id { get; set; }
        public string estc_Nombre { get; set; }

        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}