// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbHabitaciones
    {
        public tbHabitaciones()
        {
            tbPaquetes = new HashSet<tbPaquetes>();
        }

        public int habi_Id { get; set; }
        public string habi_Nombre { get; set; }
        public int hote_Id { get; set; }
        public int cath_Id { get; set; }
        public decimal? habi_Precio { get; set; }

        public virtual tbCategoriasHabitacional cath { get; set; }
        public virtual tbHoteles hote { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetes { get; set; }
    }
}