// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbHoteles
    {
        public tbHoteles()
        {
            tbHabitaciones = new HashSet<tbHabitaciones>();
        }

        public int hote_Id { get; set; }
        public string hote_Nombre { get; set; }
        public int ciud_Id { get; set; }
        public string hote_DireccionExacta { get; set; }
        public int? hote_Estellas { get; set; }

        public virtual tbCiudades ciud { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitaciones { get; set; }
    }
}