// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbDepartamentos = new HashSet<tbDepartamentos>();
        }

        public int pais_Id { get; set; }
        public string pais_Nombre { get; set; }
        public int cont_Id { get; set; }

        public virtual tbContinentes cont { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentos { get; set; }
    }
}