// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbPaquetes
    {
        public tbPaquetes()
        {
            tbReservaciones = new HashSet<tbReservaciones>();
        }

        public int paqu_Id { get; set; }
        public string paqu_Nombre { get; set; }
        public string paqu_Imagen { get; set; }
        public int vuel_Id { get; set; }
        public int habi_Id { get; set; }
        public int paqu_Personas { get; set; }
        public decimal paqu_Precio { get; set; }

        public virtual tbHabitaciones habi { get; set; }
        public virtual tbVuelos vuel { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
    }
}