// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbReservaciones = new HashSet<tbReservaciones>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int pers_Id { get; set; }
        public string pers_Nombres { get; set; }
        public string pers_Apellidos { get; set; }
        public string pers_Identidad { get; set; }
        public int estc_Id { get; set; }
        public DateTime pers_FechaNacimiento { get; set; }
        public string pers_Sexo { get; set; }
        public string pers_Celular { get; set; }
        public bool? pers_EsEmpleado { get; set; }

        public virtual tbEstadosCiviles estc { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}