// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbReservaciones
    {
        public int rese_Id { get; set; }
        public int paqu_Id { get; set; }
        public int pers_Id { get; set; }

        public virtual tbPaquetes paqu { get; set; }
        public virtual tbPersonas pers { get; set; }
    }
}