// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class tbVuelos
    {
        public tbVuelos()
        {
            tbBilletesAvion = new HashSet<tbBilletesAvion>();
            tbPaquetes = new HashSet<tbPaquetes>();
        }

        public int vuel_Id { get; set; }
        public DateTime vuel_FechaSalida { get; set; }
        public DateTime vuel_FechaLlegada { get; set; }
        public int vuel_AeropuertoSalida { get; set; }
        public int vuel_AeropuertoLlegada { get; set; }
        public int agenvuel_Id { get; set; }

        public virtual tbAeropuertos vuel_AeropuertoLlegadaNavigation { get; set; }
        public virtual tbAeropuertos vuel_AeropuertoSalidaNavigation { get; set; }
        public virtual ICollection<tbBilletesAvion> tbBilletesAvion { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetes { get; set; }
    }
}