// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class VW_tbVuelos
    {
        public int vuel_Id { get; set; }
        public DateTime vuel_FechaSalida { get; set; }
        public DateTime vuel_FechaLlegada { get; set; }
        public int vuel_AeropuertoSalida { get; set; }
        public int vuel_AeropuertoLlegada { get; set; }
        public int agenvuel_Id { get; set; }
        public string agenvuel_Nombre { get; set; }
        public string vuel_Info { get; set; }
        public int pais_Id { get; set; }
        public string pais_Nombre { get; set; }
    }
}