// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agence.Entities.Entities
{
    public partial class VW_tbHabitaciones
    {
        public int habi_Id { get; set; }
        public string habi_Nombre { get; set; }
        public int hote_Id { get; set; }
        public string hote_Nombre { get; set; }
        public int cath_Id { get; set; }
        public string cath_Nombre { get; set; }
        public decimal? habi_Precio { get; set; }
    }
}